# Generated by Django 2.2.13 on 2020-06-25 00:31

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=20)),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='')),
            ],
        ),
    ]
